# Generated by Django 6.0.5 on 2026-05-21 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Ustawienie',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=30, unique=True, verbose_name='Nr dokumentu')),
                ('doc_type', models.CharField(choices=[('office', 'Office'), ('telefon', 'Telefon'), ('produkcja', 'Produkcja')], max_length=10, verbose_name='Typ')),
                ('operation', models.CharField(choices=[('wydanie', 'Wydanie'), ('zwrot', 'Zwrot')], max_length=10, verbose_name='Operacja')),
                ('doc_date', models.DateField(verbose_name='Data')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Przekazujący')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Przyjmujący')),
                ('receiver_email', models.EmailField(max_length=254, verbose_name='Email przyjmującego')),
                ('network_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa sieciowa')),
                ('sig_issuer', models.TextField(blank=True, default='', verbose_name='Podpis przekazującego')),
                ('sig_receiver', models.TextField(blank=True, default='', verbose_name='Podpis przyjmującego')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protokół',
                'verbose_name_plural': 'Protokoły',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('equipment_type', models.CharField(blank=True, default='', max_length=100)),
                ('manufacturer_model', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('internal_number', models.CharField(blank=True, default='', max_length=100)),
                ('phone_type', models.CharField(blank=True, default='', max_length=100)),
                ('imei', models.CharField(blank=True, default='', max_length=50)),
                ('internal_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('sim_number', models.CharField(blank=True, default='', max_length=100)),
                ('pin_phone', models.CharField(blank=True, default='', max_length=20)),
                ('pin_sim', models.CharField(blank=True, default='', max_length=20)),
                ('acc_foil', models.BooleanField(default=False)),
                ('acc_case', models.BooleanField(default=False)),
                ('acc_charger', models.BooleanField(default=False)),
                ('acc_headphones', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='protokoly.document')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
