# Generated by Django 6.0.5 on 2026-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokoly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issuer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email przekazującego'),
        ),
    ]
