# Generated by Django 5.2.14 on 2026-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protokoly", "0003_add_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="send_to_accounting",
            field=models.BooleanField(
                default=True, verbose_name="Wyślij do księgowości"
            ),
        ),
    ]
